### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by rex5225** [thefyfy/ScreenlyManager#1]
Hi Jeremy,

I like the idea of this app. Could you provide a installation manual for it?

Thanks!

**Comment by thefyfy** [comment]
Hi,

Sure : you have to download latest zip Archive from Releases. Unzip it and run the file named "ScreenlyManager_[version].appxbundle".
Then, when app show up, you have to register your first raspberry on the left pane and then you're good to go.
If you have any questions don't hesitate to contact me.

Thanks for your feedback

**Comment by rex5225** [comment]
Thanks for the reply!

I assume this app works only on windows correct? Is it available on raspbian?

Thanks!

**Comment by thefyfy** [comment]
Unfortunatly, this app works only on Windows.

**Comment by rsmartins78** [comment]
This app can run in a docker container?
