### ISSUE TITLE
Certificate Expired.  Can't Install

### ISSUE THREAD

**Issue by iAutom8** [thefyfy/ScreenlyManager#10]
The previous issue was closed but does not resolve the issue as issue is different.

The solution linked works for first certificate error.  This is the following issue I get because the certificate is expired.  It is not the same issue.  

Please see issue 8.

Merci

_Originally posted by @iAutom8 in https://github.com/thefyfy/ScreenlyManager/issues/8#issuecomment-494046103_

**Comment by thefyfy** [comment]
A new release was just released. Let me know if everything fine for you.

**Comment by iAutom8** [comment]
Works after installing the certificate manually (see https://github.com/thefyfy/ScreenlyManager/issues/4#issue-381181259).  Not ideal but works.  Thanks.
