### ISSUE TITLE
Need help to understand the techniques you have used to make it app working..

### ISSUE THREAD

**Issue by vdj69** [thefyfy/ScreenlyManager#13]
Hi there!

This app looks awesome. 

I'm don't know .net so I need help to understand the techniques you have used to make it app working i.e fetching the information and controlling the screenly-ose. 

Could you please enlighten me as to how I can do the same in Nodejs or Python?

**Comment by thefyfy** [comment]
Hi,

Quite simple : I made a configuration file (db.json) where I store all remote IP of Raspberry (and everything I need to connect to API of each).
When app is launched, I read that file and try to connect to all.
Then, when user select one of them on the left, I grab all assets of this one to show informations on the right.

Thats all !
________________________________
De : vdj69 <notifications@github.com>
Envoyé : mardi 29 septembre 2020 17:08
À : thefyfy/ScreenlyManager <ScreenlyManager@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [thefyfy/ScreenlyManager] Need help to understand the techniques you have used to make it app working.. (#13)


Hi there!

This app looks awesome.

I'm don't know .net so I need help to understand the techniques you have used to make it app working i.e fetching the information and controlling the screenly-ose.

Could you please enlighten me as to how I can do the same in Nodejs or Python?
