### ISSUE TITLE
request for a compiled program

### ISSUE THREAD

**Issue by adneg** [thefyfy/ScreenlyManager#3]
Welcome. I wanted to write something about similar functionality. But I see that you did it before. Is there any possibility that you will share the program. I do not know C#. I do not want to fight with compilation and environment to build it. Is it possible to share  portable exec app?

**Comment by thefyfy** [comment]
Hi, there is no "portable version".
But there is a compiled version in the release section: https://github.com/thefyfy/ScreenlyManager/releases

**Comment by adneg** [comment]
Thank you. 
Your program looks professional in the attached pictures. I try install last release. 

I should run
Add-AppDevPackage.ps1  ?

I get this error:
`ErrorPackageUnsigned = Error: The package or bundle is not digitally signed or its signature is corrupted.`


I do not know how to install it on windows.
 I am sorry I am a linux user / golang programmer. Can you explain?

I have a question about licenses. I would like to use your application. If I will install it. Can I?

**Comment by adneg** [comment]
Ok, Probably I need windows 10. 

https://www.howtogeek.com/285410/how-to-install-.appx-or-.appxbundle-software-on-windows-10/

I will test it.

Thank you very much for the contact.
