### ISSUE TITLE
Certificate error #2

### ISSUE THREAD

**Issue by mkimbrough** [thefyfy/ScreenlyManager#4]
I got the same certificate error that MLFJBekker saw. I replied to his request but realized it was closed so I'll post the answer here. This produced no errors and the app appears to be installed correctly.
Right click on APPX file
Click Properties
Click Digital Signatures
Select Signature from the list
Click Details
Click View Certificate
Click Install Certificate
Instead of installing the certificate in the current user's Store location, select "Local Machine"and then selected "Trusted Root Certification Authorities

**Comment by thefyfy** [comment]
Thank's for details @mkimbrough
