### ISSUE TITLE
Crash after adding new RPi

### ISSUE THREAD

**Issue by Noreu** [thefyfy/ScreenlyManager#6]
Hello,

Release 1.0.15.0
When I add a new RPi, I clik OK on the popup, then the screen crashed.
Try with previous version, same error.

Any idea ?

**Comment by Noreu** [comment]
I have this error :
JsonReaderException : Unexpected character encountered while parsing value: S. Path '', line 0, position 0.

**Comment by Noreu** [comment]
In GetAssetsAsync func from Device.cs, line 
`this.Assets = JsonConvert.DeserializeObject<List<Asset>>(resultJson);`
doesn't work. The crash is here.
resultJson return assets from RPi, no problem here.

**Comment by Noreu** [comment]
Work after a screenly upgrade.
The problem is there a boolean true / false variable for is_active in previous version, and now this variable is 0 / 1.

**Comment by thefyfy** [comment]
Sorry for delay and thank you for feedbak on your issue.
