### ISSUE TITLE
Installation Error With Certificate

### ISSUE THREAD

**Issue by iAutom8** [thefyfy/ScreenlyManager#8]
When installing the application I get the following error :

App installation failed with error message: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file. (0x800b0101)

It appears the certificate expired on March 15th.  Would it be possible to include an updated certificate?  I will look at compiling my own copy but until then I wanted to try it out.

Merci, Alain

**Comment by thefyfy** [comment]
Solution given on [issue #4](https://github.com/thefyfy/ScreenlyManager/issues/4#issue-381181259)

**Comment by iAutom8** [comment]
The solution works for first certificate error.  This is the following issue I get because the certificate is expired.  It is not the same issue.  Merci
