### ISSUE TITLE
Unable to load Assets (API url) "Error while getting assets."

### ISSUE THREAD

**Issue by Softhies** [thefyfy/ScreenlyManager#9]
missing slash bettween api version (example: /api/v1.2assets/5b4876a3e8f44ad2ac5d2b8566509f4c)

**Comment by thefyfy** [comment]
You have to put the slash in config like it shows by the placeholder : 
![image](https://user-images.githubusercontent.com/1229018/58187141-86dc7e00-7cb6-11e9-8d0b-c0af41753eb5.png)

**Comment by Softhies** [comment]
Uhh.. i'm sorry.. i did'nt read this.
